name: Semantic release

on:
  push:
    branches:
      - main
      - beta
  workflow_dispatch:

jobs:
  release:
    name: Semantic release
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: "☁️ checkout repository"
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      
      - name: "🔧 setup node"
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: "🔧 install npm@latest"
        run: npm i -g npm@latest

      - name: "🚀 release"
        id: semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          NPM_PACKAGE_ROOT: "npm"
        uses: open-sauced/release@v2.2.0

    outputs:
        release-tag: ${{ steps.semantic-release.outputs.release-tag }}

        
  build:
    needs:
      - release
    runs-on: ubuntu-latest
    permissions:
      contents: write # release changes require contents write
    strategy:
      matrix:
        goos: [darwin, linux, windows]
        goarch: [amd64, arm64]

    steps:
    - name: Set up Go
      uses: actions/setup-go@fac708d6674e30b6ba41289acaab6d4b75aa0753 # v4.0.1
      with:
        go-version: 1.21

    - name: Check out code
      uses: actions/checkout@v3

    - name: Build and upload Go binaries
      env:
        GH_TOKEN: ${{ github.token }}
      run: |
        GOOS=${{ matrix.goos }} GOARCH=${{ matrix.goarch }} go build -o build/pizzarino-cli-${{ matrix.goos }}-${{ matrix.goarch }}
        gh release upload ${{ needs.release.outputs.release-tag }} build/pizzarino-cli-${{ matrix.goos }}-${{ matrix.goarch }}
